# Generated by Django 4.2.1 on 2023-05-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_jop_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='Published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jop',
            name='Vacancy',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='jop',
            name='experiense',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jop',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
